In [1]:
import numpy as np

In [2]:
myarr = np.array([5,6,4,88,44])

In [3]:
myarr

array([ 5,  6,  4, 88, 44])

In [4]:
myarr[0]

np.int64(5)

In [5]:
myarr = np.array([5,6,4,88,44], np.int32) #np.int32 this is used for memory managment 

In [6]:
myarr[0] #now the output is in 32bit

np.int32(5)

In [7]:
myarr[3]

np.int32(88)

In [8]:
myarr2 = np.array([[1,2,3,4,5,6]]) #we have created a 2D - multidimention array 

In [9]:
myarr2[0,2]

np.int64(3)

In [10]:
myarr2[0, 3]

np.int64(4)

In [11]:
myarr.shape

(5,)

In [12]:
myarr2.shape

(1, 6)

In [13]:
myarr2[0,3] = 1212 #this will place 

In [14]:
myarr

array([ 5,  6,  4, 88, 44], dtype=int32)

In [15]:
myarr2

array([[   1,    2,    3, 1212,    5,    6]])

In [16]:
myarr3 = np.array([[1,2,3]])

In [17]:
myarr3

array([[1, 2, 3]])

# Array Creation : Conversion from python structure

In [18]:
listarray = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [19]:
listarray

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [20]:
listarray.shape

(3, 3)

In [21]:
listarray.size

9

In [22]:
np.array({34,25,55}) #it is not efficent to create an dtype-object, use int/float

array({25, 34, 55}, dtype=object)

In [23]:
zeros = np.zeros((2,5)) #this gives use zeros in array of 2 row and 5 column

In [24]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [25]:
zeros.shape

(2, 5)

In [26]:
rng = np.arange(15) #this is like a range in python it will go upto 0 to 14.

In [27]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [28]:
lspace = np.linspace(1,50,5) # 1 to 50 with printing of 5 element  #inshort it print the diffrence between element

In [29]:
lspace

array([ 1.  , 13.25, 25.5 , 37.75, 50.  ])

In [30]:
lspace1 = np.linspace(1,50,3) 

In [31]:
lspace1

array([ 1. , 25.5, 50. ])

In [32]:
lspace = np.linspace(1,50,10)

In [33]:
lspace

array([ 1.        ,  6.44444444, 11.88888889, 17.33333333, 22.77777778,
       28.22222222, 33.66666667, 39.11111111, 44.55555556, 50.        ])

In [34]:
emp = np.empty((4,6))

In [35]:
emp

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        1.29062025e-306, 1.89146896e-307, 7.56571288e-307],
       [3.11525958e-307, 1.24610723e-306, 1.37962320e-306,
        1.29060871e-306, 2.22518251e-306, 1.33511969e-306],
       [1.78022342e-306, 1.05700345e-307, 3.11525958e-307,
        1.69118108e-306, 8.06632139e-308, 1.20160711e-306],
       [1.69119330e-306, 1.29062229e-306, 6.89804133e-307,
        1.33511969e-306, 6.89807867e-307, 2.22522596e-306]])

In [36]:
emp_like = np.empty_like(myarr)

In [37]:
emp_like

array([1246118304,        514,          0,          0,          1],
      dtype=int32)

In [38]:
ide = np.identity(45)

In [39]:
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [40]:
ide.shape

(45, 45)

In [41]:
arr = np.arange(99)

In [42]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [43]:
arr.reshape(3,33)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [44]:
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [45]:
arr = arr.ravel()

In [46]:
arr.shape #this represent the arr.ravel has 99 element in it including 0 to 98

(99,)

In [47]:
x = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [48]:
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [49]:
print(x)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [50]:
x.sum(axis=0)

array([12, 15, 18])

In [51]:
x.sum(axis=1)

array([ 6, 15, 24])

In [52]:
x.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [53]:
x.flat

In [54]:
for i in x.flat:
    print(x)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [55]:
for i in x.flat:
    print(i)

1
2
3
4
5
6
7
8
9


In [56]:
x.nbytes


72

In [57]:
one = np.array([1,2,3,4,5,6])

In [58]:
one

array([1, 2, 3, 4, 5, 6])

In [59]:
one.argmax()

np.int64(5)

In [60]:
one.argmin()

np.int64(0)

In [61]:
one.argsort()

array([0, 1, 2, 3, 4, 5])

In [62]:
two = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [63]:
two.argmin()

np.int64(0)

In [64]:
two.argmax()

np.int64(8)

In [65]:
two.argsort()

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

In [66]:
two.argmax(axis = 1)

array([2, 2, 2])

In [67]:
two.argmax(axis = 0)

array([2, 2, 2])

In [68]:
two.argmin(axis = 1)

array([0, 0, 0])

In [69]:
two.argmin(axis = 0)

array([0, 0, 0])

In [70]:
ar1 = np.array([[1,2,3],
               [4,5,6],
               [7,8,9]])
               

In [71]:
ar2 = np.array([[1,5,6],
               [4,2,3],
               [3,8,1]])
               

In [72]:
ar1 + ar2 #this is a matrix addition

array([[ 2,  7,  9],
       [ 8,  7,  9],
       [10, 16, 10]])

In [73]:
ar1 * ar2 #this is a matrix multiplication

array([[ 1, 10, 18],
       [16, 10, 18],
       [21, 64,  9]])

In [74]:
ar1 - ar2 #this is a matrix sunstraction

array([[ 0, -3, -3],
       [ 0,  3,  3],
       [ 4,  0,  8]])

In [75]:
ar1 / ar2 #this is a matrix division

array([[1.        , 0.4       , 0.5       ],
       [1.        , 2.5       , 2.        ],
       [2.33333333, 1.        , 9.        ]])

In [76]:
np.sqrt(ar1)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [77]:
 ar1.sum()

np.int64(45)

In [78]:
ar1.max()

np.int64(9)

In [79]:
ar1.min()

np.int64(1)

In [80]:
ar1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [81]:
np.where(ar1>5) #it will return 1 array of row and the 2 array of column 

(array([1, 2, 2, 2]), array([2, 0, 1, 2]))

In [82]:
type(np.where(ar1>5)) #this is return in tuple

tuple

In [83]:
np.count_nonzero(ar1) #it returns number of non zero element

9

In [84]:
np.nonzero(ar1)#it returns index of non zero element

(array([0, 0, 0, 1, 1, 1, 2, 2, 2]), array([0, 1, 2, 0, 1, 2, 0, 1, 2]))