#**Array indexing**

In [1]:
import numpy as np

In [2]:
arr = np.array([1,2,3,4,5,6,7,8,9])

In [3]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
arr[0] = 99

In [5]:
arr

array([99,  2,  3,  4,  5,  6,  7,  8,  9])

In [6]:
arr[5] = 101

In [7]:
arr

array([ 99,   2,   3,   4,   5, 101,   7,   8,   9])

In [8]:
arr[-1] = 201

In [9]:
arr

array([ 99,   2,   3,   4,   5, 101,   7,   8, 201])

In [10]:
arr[-1]

201

In [11]:
arr[-2]

8

In [12]:
arr2 = np.array([[1,2,3], [4,5,6], [7,8,9]])

In [13]:
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
arr2[0,0] = 99

In [15]:
arr2

array([[99,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [16]:
arr2[0,1]

2

In [17]:
arr2[2,2]

9

#**Array Slicing**

In [18]:
arr1 = np.array([0,1,2,3,4,5,6,7,8,9])


In [19]:
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
arr1[4:]

array([4, 5, 6, 7, 8, 9])

In [21]:
arr1[4:6]

array([4, 5])

In [22]:
arr1[:-1:2]

array([0, 2, 4, 6, 8])

In [23]:
arr1[::2]

array([0, 2, 4, 6, 8])

In [24]:
arr1[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

#**Array Concatination**

In [25]:
arr1 = np.array([1,2,3])

In [26]:
arr2 = np.array([4,5,6])

In [27]:
arr =np.concatenate((arr1, arr2))

In [28]:
arr

array([1, 2, 3, 4, 5, 6])

In [29]:
print(arr)

[1 2 3 4 5 6]


In [30]:
d2arr1 = np.array([[1,2,3], [4,5,6]])

In [31]:
d2arr2= np.array([[7,8,9],[10,11,12]])

In [32]:
d2arr = np.concatenate((d2arr1, d2arr2))

In [33]:
d2arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [34]:
axis_arr1 = np.array([[1,2,3], [4,5,6]]) #this is 2 x 3

In [35]:
axis_arr2 = np.array([[7,8,9],[10,11,12]])#this is 2 x 3

In [36]:
axis_arr = np.concatenate((d2arr1, d2arr2), axis = 1)

In [37]:
axis_arr #this is 2 x 6

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [38]:
arr2d = np.array([[1, 2], [3, 4]])


In [39]:
arr1d = np.array([5, 6])


In [40]:
arr1d_2d = arr1d.reshape(1, -1)  # Reshape to a single row (1, -1) or column (-1, 1)


In [41]:
result = np.concatenate((arr2d, arr1d_2d), axis=0)


In [42]:
result

array([[1, 2],
       [3, 4],
       [5, 6]])

In [43]:
harr1 = np.array([1,2,3])

In [44]:
harr2 = np.array([4,5,9])

In [45]:
harr = np.hstack((arr1, arr2))

In [46]:
harr

array([1, 2, 3, 4, 5, 6])

In [47]:
varr1 = np.array([1,2,3])

In [48]:
varr2 = np.array([4,5,9])

In [49]:
varr = np.vstack((arr1, arr2))

In [50]:
varr

array([[1, 2, 3],
       [4, 5, 6]])

#**Hacker Rank**

**Task 1**

In [51]:
a = np.array([0,1,2,8,-10,-15], float)

In [52]:
a[::-1]

array([-15., -10.,   8.,   2.,   1.,   0.])

**Task 2**

In [53]:
b = np.array([0,1,2,3,4,5,6,7,8])

In [54]:
b.shape = (3,3)

In [55]:
b

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

**Task 3**

In [56]:
A = np.array([[1,2,3],[4,5,6]])

In [57]:
A.transpose()

array([[1, 4],
       [2, 5],
       [3, 6]])

In [58]:
B = np.array([[1,2,3],[4,5,6]])

In [59]:
B.flatten()

array([1, 2, 3, 4, 5, 6])

**Task 4**

In [60]:
np.concatenate((A, B), axis = 0)

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

**Task 5

In [61]:
print(np.zeros((3,3)))

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [62]:
print(np.ones((3,3)))

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


**Task 6**

In [63]:
print (np.identity(5) )#3 is for  dimension 3 X 3


[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


**Task 7**

In [64]:
print(np.add(A,B))

[[ 2  4  6]
 [ 8 10 12]]


In [65]:
print(np.subtract(A,B))

[[0 0 0]
 [0 0 0]]


In [66]:
print(np.multiply(A,B))

[[ 1  4  9]
 [16 25 36]]


In [67]:
print(np.divide(A,B))

[[1. 1. 1.]
 [1. 1. 1.]]


In [68]:
print(np.mod(A,B))

[[0 0 0]
 [0 0 0]]


In [69]:
print(np.power(A,B))

[[    1     4    27]
 [  256  3125 46656]]


**Task 8**


In [70]:
C = np.array([1.6,2.2,3.5,4.0,5,6])

In [71]:
print(np.floor(C)  ) #eturn the floor values of each element

[1. 2. 3. 4. 5. 6.]


In [72]:
print(np.ceil(C)  )#rounds up floating point element(s) in an array to the nearest integer greater than or equal to the array element.

[2. 3. 4. 4. 5. 6.]


In [73]:
print(np.rint(C)  )# a mathematical function that rounds elements of the array to the nearest integer.

[2. 2. 4. 4. 5. 6.]


**Task 9**

In [74]:
c = np.array([[1,2,3],[4,5,6]])

In [75]:
d = np.sum( (c), axis =0)

In [76]:
d

array([5, 7, 9])

In [77]:
e = np.prod((d))

In [78]:
e

315

**Task 10**

In [79]:
f = np.array([[1,2,3],[4,5,6]])

In [80]:
np.min(f, axis =1)

array([1, 4])

In [81]:
np.max(f)

6

**Task 11**

In [82]:
M =np.array([[1,2,3],[4,5,6],[7,8,9]])

In [83]:
np.mean(M)

5.0

In [84]:
np.mean(M, axis = 1) #task with axis = 1

array([2., 5., 8.])

In [85]:
V =np.array([[1,2,3],[4,5,6],[7,8,9]])

In [86]:
np.var(V)

6.666666666666667

In [87]:
np.var(V,  axis = 0)#task with axis = 0

array([6., 6., 6.])

In [88]:
S =np.array([[1,2,3],[4,5,6],[7,8,9]])

In [89]:
np.std(S) #task with axis = none (By Default it is none)

2.581988897471611

**Task 12**


In [90]:
Str1 = np.array([1,2,3])

In [91]:
Str2 = np.array([4,5,6])

In [92]:
np.dot(Str1, Str2)

32

In [93]:
np.cross(Str1, Str2)

array([-3,  6, -3])

**Task 13**

In [100]:
g =np.array([1,1])

In [101]:
h = np.array([5,4])

In [104]:
np.inner(g,h)

9

In [105]:
np.outer(g,h)

array([[5, 4],
       [5, 4]])

In [106]:
np.poly([-1, 1, 1, 10])

array([  1., -11.,   9.,  11., -10.])

In [107]:
np.polyval([1, -2, 0, 2], 4)

34

In [108]:
 np.linalg.det([[1 , 2], [2, 1]])

-2.9999999999999996

In [110]:
vals, vecs = np.linalg.eig([[1 , 2], [2, 1]])

In [114]:
print (vals)

[ 3. -1.]


In [115]:
print(vecs)

[[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]


In [116]:
np.linalg.inv([[1 , 2], [2, 1]])

array([[-0.33333333,  0.66666667],
       [ 0.66666667, -0.33333333]])